x-google-marketplace:

  schemaVersion: v2

  applicationApiVersion: v1beta1

  publishedVersion: "3.0.2-b1"
  publishedVersionMetadata:
    releaseNote: >-
      Initial release.
    releaseTypes:
      - Feature
    recommended: true

  clusterConstraints:
    resources:
      - replicas: 3
        requests:
          cpu: 6200m
          memory: 10Gi
        affinity:
          simpleNodeAffinity:
            type: REQUIRE_ONE_NODE_PER_REPLICA

  images:

    '':
      properties:
        pulsar.image.broker.repository:
          type: REPO_WITH_REGISTRY
        pulsar.image.broker.tag:
          type: TAG

    ubbagent:
      properties:
        ubbagent-image-repository:
          type: FULL

    broker-sts:
      properties:
        pulsar.image.brokerSts.repository:
          type: REPO_WITH_REGISTRY
        pulsar.image.brokerSts.tag:
          type: TAG

    function:
      properties:
        pulsar.image.function.repository:
          type: REPO_WITH_REGISTRY
        pulsar.image.function.tag:
          type: TAG

    zookeeper:
      properties:
        pulsar.image.zookeeper.repository:
          type: REPO_WITH_REGISTRY
        pulsar.image.zookeeper.tag:
          type: TAG

    bookkeeper:
      properties:
        pulsar.image.bookkeeper.repository:
          type: REPO_WITH_REGISTRY
        pulsar.image.bookkeeper.tag:
          type: TAG
 
    proxy:
      properties:
        pulsar.image.proxy.repository:
          type: REPO_WITH_REGISTRY
        pulsar.image.proxy.tag:
          type: TAG

    bastion:
      properties:
        pulsar.image.bastion.repository:
          type: REPO_WITH_REGISTRY
        pulsar.image.bastion.tag:
          type: TAG

    beam:
      properties:
        pulsar.image.pulsarBeam.repository:
          type: REPO_WITH_REGISTRY
        pulsar.image.pulsarBeam.tag:
          type: TAG
 
    burnell:
      properties:
        pulsar.image.burnell.repository:
          type: REPO_WITH_REGISTRY
        pulsar.image.burnell.tag:
          type: TAG
 
    burnell-log-collector:
      properties:
        pulsar.image.burnellLogCollector.repository:
          type: REPO_WITH_REGISTRY
        pulsar.image.burnellLogCollector.tag:
          type: TAG
 
    sql:
      properties:
        pulsar.image.pulsarSQL.repository:
          type: REPO_WITH_REGISTRY
        pulsar.image.pulsarSQL.tag:
          type: TAG

    tardigrade:
      properties:
        pulsar.image.tardigrade.repository:
          type: REPO_WITH_REGISTRY
        pulsar.image.tardigrade.tag:
          type: TAG

    heartbeat:
      properties:
        pulsar.image.pulsarHeartbeat.repository:
          type: REPO_WITH_REGISTRY
        pulsar.image.pulsarHeartbeat.tag:
          type: TAG

    admin-console:
      properties:
        pulsar.image.pulsarAdminConsole.repository:
          type: REPO_WITH_REGISTRY
        pulsar.image.pulsarAdminConsole.tag:
          type: TAG

    admin-console-nginx:
      properties:
        pulsar.image.pulsarAdminConsoleNginx.repository:
          type: FULL

    prometheus:
      properties:
        pulsar.kube-prometheus-stack.prometheus.prometheusSpec.image.repository:
          type: REPO_WITH_REGISTRY
        pulsar.kube-prometheus-stack.prometheus.prometheusSpec.image.tag:
          type: TAG

    prometheus-node-exporter:
      properties:
        pulsar.kube-prometheus-stack.prometheus-node-exporter.image.repository:
          type: REPO_WITH_REGISTRY
        pulsar.kube-prometheus-stack.prometheus-node-exporter.image.tag:
          type: TAG

    prometheus-operator:
      properties:
        pulsar.kube-prometheus-stack.prometheusOperator.image.repository:
          type: REPO_WITH_REGISTRY
        pulsar.kube-prometheus-stack.prometheusOperator.image.tag:
          type: TAG

    prometheus-operator-admission-patch:
      properties:
        pulsar.kube-prometheus-stack.prometheusOperator.admissionWebhooks.patch.image.repository:
          type: REPO_WITH_REGISTRY
        pulsar.kube-prometheus-stack.prometheusOperator.admissionWebhooks.patch.image.tag:
          type: TAG

    prometheus-operator-configmap-reload:
      properties:
        pulsar.kube-prometheus-stack.prometheusOperator.configmapReloadImage.repository:
          type: REPO_WITH_REGISTRY
        pulsar.kube-prometheus-stack.prometheusOperator.configmapReloadImage.tag:
          type: TAG

    prometheus-operator-config-reloader:
      properties:
        pulsar.kube-prometheus-stack.prometheusOperator.prometheusConfigReloaderImage.repository:
          type: REPO_WITH_REGISTRY
        pulsar.kube-prometheus-stack.prometheusOperator.prometheusConfigReloaderImage.tag:
          type: TAG

    kube-state-metrics:
      properties:
        pulsar.kube-prometheus-stack.kube-state-metrics.image.repository:
          type: REPO_WITH_REGISTRY
        pulsar.kube-prometheus-stack.kube-state-metrics.image.tag:
          type: TAG

    grafana:
      properties:
        pulsar.kube-prometheus-stack.grafana.image.repository:
          type: REPO_WITH_REGISTRY
        pulsar.kube-prometheus-stack.grafana.image.tag:
          type: TAG

    grafana-sidecar:
      properties:
        pulsar.kube-prometheus-stack.grafana.sidecar.image.repository:
          type: REPO_WITH_REGISTRY
        pulsar.kube-prometheus-stack.grafana.sidecar.image.tag:
          type: TAG

  deployerServiceAccount:
    description: >
      creates application resources
    roles:
    - type: ClusterRole
      rulesType: CUSTOM
      rules:
      - apiGroups: ['admissionregistration.k8s.io','apiextensions.k8s.io','apiregistration.k8s.io','apps','authentication.k8s.io','authorization.k8s.io','batch','certificates.k8s.io','coordination.k8s.io','core','discovery.k8s.io','events.k8s.io','flowcontrol.apiserver.k8s.io','internal.apiserver.k8s.io','networking.k8s.io','node.k8s.io','policy','rbac.authorization.k8s.io','scheduling.k8s.io','storage.k8s.io','']
        resources: ['*']
        verbs: ['*']

properties:

  name:
    type: string
    x-google-marketplace:
      type: NAME

  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE

  reportingSecret:
    type: string
    x-google-marketplace:
      type: REPORTING_SECRET

  pulsar.default_storage.existingStorageClassName:
    type: string
    x-google-marketplace:
      type: STORAGE_CLASS
      storageClass:
        type: SSD

  burnell-sa:
    type: string
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        description: >
          service account used for the burnell component of pulsar
        roles:
          - type: Role
            rulesType: CUSTOM
            rules:
              - apiGroups: ['']
                resources: ['secrets']
                verbs: ['get', 'create', 'list']
              - apiGroups: ['']
                resources: ['namespaces']
                verbs: ['list']
              - apiGroups: ['apps']
                resources: ['deployments', 'statefulsets']
                verbs: ['list']

  function-sa:
    type: string
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        description: >
          service account used for the function component of pulsar
        roles:
          - type: Role
            rulesType: CUSTOM
            rules:
              - apiGroups: ['']
                resources: ['pods']
                verbs: ['list']
              - apiGroups: ['']
                resources: ['secrets']
                verbs: ['*']
              - apiGroups: ['']
                resources: ['services']
                verbs: ['get', 'create', 'delete']
              - apiGroups: ['apps']
                resources: ['statefulsets']
                verbs: ['get', 'create', 'delete']

  pulsar-heartbeat-sa:
    type: string
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        description: >
          service account used for the pulsarheartbeat component of pulsar
        roles:
          - type: Role
            rulesType: CUSTOM
            rules:
              - apiGroups: ['']
                resources: ['pods']
                verbs: ['list']
              - apiGroups: ['apps']
                resources: ['deployments','statefulsets']
                verbs: ['list']

  grafana-sa:
    type: string
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        description: >
          service account used for the grafana component of pulsar
        roles:
          - type: Role
            rulesType: CUSTOM
            rules:
              - apiGroups: ['extensions']
                resources: ['podsecuritypolicies']
                verbs: ['use']
          - type: ClusterRole
            rulesType: CUSTOM
            rules:
              - apiGroups: ['']
                resources: ['secrets', 'configmaps']
                verbs: ['get', 'watch', 'list']

  webhook-admiss-sa:
    type: string
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        description: >
          service account used for the kube-prometheus-admission component of pulsar
        roles:
          - type: Role
            rulesType: CUSTOM
            rules:
              - apiGroups: ['']
                resources: ['secrets']
                verbs: ['get', 'create']
          - type: ClusterRole
            rulesType: CUSTOM
            rules:
              - apiGroups: ['admissionregistration.k8s.io']
                resources: ['validatingwebhookconfigurations','mutatingwebhookconfigurations']
                verbs: ['get', 'update']
              - apiGroups: ['policy']
                resources: ['podsecuritypolicies']
                verbs: ['use']

  prom-operator-sa:
    type: string
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        description: >
          service account used for the kube-prometheus-operator component of pulsar
        roles:
          - type: ClusterRole
            rulesType: CUSTOM
            rules:
              - apiGroups: ['monitoring.coreos.com']
                resources: ['alertmanagers','alertmanagers/finalizers','alertmanagerconfigs','prometheuses','prometheuses/finalizers','thanosrulers','thanosrulers/finalizers','servicemonitors','podmonitors','probes','prometheusrules']
                verbs: ['*']
              - apiGroups: ['apps']
                resources: ['statefulsets']
                verbs: ['*']
              - apiGroups: ['']
                resources: ['configmaps','secrets']
                verbs: ['*']
              - apiGroups: ['']
                resources: ['pods']
                verbs: ['list', 'delete']
              - apiGroups: ['']
                resources: ['services','services/finalizers','endpoints']
                verbs: ['get','create','update','delete']
              - apiGroups: ['']
                resources: ['nodes']
                verbs: ['list','watch']
              - apiGroups: ['']
                resources: ['namespaces']
                verbs: ['get','list','watch']
              - apiGroups: ['networking.k8s.io']
                resources: ['ingress']
                verbs: ['get','list','watch']
              - apiGroups: ['policy']
                resources: ['podsecuritypolicies']
                verbs: ['use']

  prometheus-sa:
    type: string
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        description: >
          service account used for the kube-prometheus-prometheus component of pulsar
        roles:
          - type: ClusterRole
            rulesType: CUSTOM
            rules:
              - apiGroups: ['']
                resources: ['nodes','nodes/metrics','services','endpoints','pods']
                verbs: ['get','list','watch']
              - apiGroups: ['networking.k8s.io']
                resources: ['ingress']
                verbs: ['get','watch','list']
              - apiGroups: ['policy']
                resources: ['podsecuritypolicies']
                verbs: ['use']

  kube-state-metrics-sa:
    type: string
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        description: >
          service account used for the kube-state-metrics component of pulsar
        roles:
          - type: ClusterRole
            rulesType: CUSTOM
            rules:
              - apiGroups: ['policy']
                resources: ['podsecuritypolicies']
                verbs: ['use']
              - apiGroups: ['certificates.k8s.io']
                resources: ['certificatesigningrequests']
                verbs: ['list', 'watch']
              - apiGroups: ['']
                resources: ['configmaps']
                verbs: ['list', 'watch']
              - apiGroups: ['batch']
                resources: ['cronjobs']
                verbs: ['list', 'watch']
              - apiGroups: ['extensions', 'apps']
                resources: ['daemonsets']
                verbs: ['list', 'watch']
              - apiGroups: ['extensions', 'apps']
                resources: ['deployments']
                verbs: ['list', 'watch']
              - apiGroups: ['']
                resources: ['endpoints']
                verbs: ['list', 'watch']
              - apiGroups: ['autoscaling']
                resources: ['horizontalpodautoscalers']
                verbs: ['list', 'watch']
              - apiGroups: ['extensions', 'networking.k8s.io']
                resources: ['ingresses']
                verbs: ['list', 'watch']
              - apiGroups: ['batch']
                resources: ['jobs']
                verbs: ['list', 'watch']
              - apiGroups: ['']
                resources: ['limitranges']
                verbs: ['list', 'watch']
              - apiGroups: ['admissionregistration.k8s.io']
                resources: ['mutatingwebhookconfigurations']
                verbs: ['list', 'watch']
              - apiGroups: ['']
                resources: ['namespaces']
                verbs: ['list', 'watch']
              - apiGroups: ['networking.k8s.io']
                resources: ['networkpolicies']
                verbs: ['list', 'watch']
              - apiGroups: ['']
                resources: ['nodes']
                verbs: ['list', 'watch']
              - apiGroups: ['']
                resources: ['persistentvolumeclaims']
                verbs: ['list', 'watch']
              - apiGroups: ['']
                resources: ['persistentvolumes']
                verbs: ['list', 'watch']
              - apiGroups: ['policy']
                resources: ['poddisruptionbudgets']
                verbs: ['list', 'watch']
              - apiGroups: ['']
                resources: ['pods']
                verbs: ['list', 'watch']
              - apiGroups: ['extensions', 'apps']
                resources: ['replicasets']
                verbs: ['list', 'watch']
              - apiGroups: ['']
                resources: ['replicationcontrollers']
                verbs: ['list', 'watch']
              - apiGroups: ['']
                resources: ['resourcequotas']
                verbs: ['list', 'watch']
              - apiGroups: ['']
                resources: ['secrets']
                verbs: ['list', 'watch']
              - apiGroups: ['']
                resources: ['services']
                verbs: ['list', 'watch']
              - apiGroups: ['apps']
                resources: ['statefulsets']
                verbs: ['list', 'watch']
              - apiGroups: ['storage.k8s.io']
                resources: ['storageclasses']
                verbs: ['list', 'watch']
              - apiGroups: ['admissionregistration.k8s.io']
                resources: ['validatingwebhookconfigurations']
                verbs: ['list', 'watch']
              - apiGroups: ['storage.k8s.io']
                resources: ['volumeattachments']
                verbs: ['list', 'watch']

  prom-node-exporter-sa:
    type: string
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        description: >
          service account used for the prometheus-node-exporter component of pulsar
        roles:
          - type: ClusterRole
            rulesType: CUSTOM
            rules:
              - apiGroups: ['extensions']
                resources: ['podsecuritypolicies']
                verbs: ['use']

required:
  - name
  - namespace

