x-google-marketplace:

  schemaVersion: v2

  applicationApiVersion: v1beta1

  publishedVersion: "2.0.11"
  publishedVersionMetadata:
    releaseNote: >-
      Initial release.
    releaseTypes:
      - Feature
    recommended: true
  
  images: {}

  deployerServiceAccount:
    description: >
      creates application resources
    roles:
    - type: ClusterRole
      rulesType: CUSTOM
      rules:
      - apiGroups: ['admissionregistration.k8s.io','apiextensions.k8s.io','apiregistration.k8s.io','apps','authentication.k8s.io','authorization.k8s.io','batch','certificates.k8s.io','coordination.k8s.io','core','discovery.k8s.io','events.k8s.io','flowcontrol.apiserver.k8s.io','internal.apiserver.k8s.io','networking.k8s.io','node.k8s.io','policy','rbac.authorization.k8s.io','scheduling.k8s.io','storage.k8s.io']
        resources: ['*']
        verbs: ['*']

properties:

  name:
    type: string
    x-google-marketplace:
      type: NAME

  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE

required:
  - name
  - namespace

