pulsar:
  fullnameOverride: pulsar-mp
  enableAntiAffinity: false
  enableTls: true
  tlsSecretName: pulsar-mp-tls
  enableTokenAuth: true

  secrets:
    key: pulsar-mp-tls-key-placeholder
    certificate: pulsar-mp-tls-certificate-placeholder
    caCertificate: pulsar-mp-tls-ca-certificate-placeholder

  restartOnConfigMapChange:
    enabled: true

  extra:
    function: true
    burnell: true
    burnellLogCollector: true
    pulsarHeartbeat: true
    pulsarAdminConsole: true

  default_storage:
    existingStorageClassName: pulsar-storage

  cert-manager:
    enabled: false

  createCertificates:
    selfSigned:
      enabled: false

  zookeeper:
    replicaCount: 1
    resources:
      requests:
        memory: 300Mi
        cpu: 0.3
    configData:
      PULSAR_MEM: "-Xms300m -Xmx300m -Djute.maxbuffer=10485760 -XX:+ExitOnOutOfMemoryError"

  bookkeeper:
    replicaCount: 1
    resources:
      requests:
        memory: 512Mi
        cpu: 0.3
    configData:
      BOOKIE_MEM: "-Xms312m -Xmx312m -XX:MaxDirectMemorySize=200m -XX:+ExitOnOutOfMemoryError"

  broker:
    component: broker
    replicaCount: 1
    ledger:
      defaultEnsembleSize: 1
      defaultAckQuorum: 1
      defaultWriteQuorum: 1
    resources:
      requests:
        memory: 600Mi
        cpu: 0.3
    configData:
      PULSAR_MEM: "-Xms400m -Xmx400m -XX:MaxDirectMemorySize=200m -XX:+ExitOnOutOfMemoryError"

  autoRecovery:
    enableProvisionContainer: true
    resources:
      requests:
        memory: 300Mi
        cpu: 0.3

  function:
    replicaCount: 1
    functionReplicaCount: 1
    resources:
      requests:
        memory: 512Mi
        cpu: 0.3
    configData:
      PULSAR_MEM: "-Xms312m -Xmx312m -XX:MaxDirectMemorySize=200m -XX:+ExitOnOutOfMemoryError"

  proxy:
    replicaCount: 1
    resources:
      requests:
        memory: 512Mi
        cpu: 0.3
    wsResources:
      requests:
        memory: 512Mi
        cpu: 0.3
    configData:
      PULSAR_MEM: "-Xms400m -Xmx400m -XX:MaxDirectMemorySize=112m"
    autoPortAssign:
      enablePlainTextWithTLS: true
    service:
      autoPortAssign:
        enabled: true

  grafanaDashboards:
    enabled: true

  pulsarAdminConsole:
    replicaCount: 1
    authMode: k8s
    createUserSecret:
      enabled: true
      user: 'admin'
      password: 'e9JYtk83*4#PM8'

  kube-prometheus-stack:
    enabled: true
    prometheusOperator:
      enabled: true
    grafana:
      enabled: true
      adminPassword: password
      sidecar:
        image:
          repository: kiwigrid/k8s-sidecar
          tag: 1.1.0
      image:
        repository: grafana/grafana
        tag: 7.3.5
    kube-state-metrics:
      image:
        repository: quay.io/coreos/kube-state-metrics
        tag: v1.9.7
    prometheus-node-exporter:
      image:
        repository: quay.io/prometheus/node-exporter
        tag: v1.0.1

  image:
    pulsarAdminConsoleNginx:
      repository: "nginxinc/nginx-unprivileged:stable-alpine"
