apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-ubbagent-config"
data:
  config.yaml: |
    # The identity section contains authentication information used
    # by the agent.
    identities:
    - name: gcp
      gcp:
        # This parameter accepts a base64-encoded JSON service
        # account key. The value comes from the reporting secret.
        encodedServiceAccountKey: $AGENT_ENCODED_KEY

    # The metrics section defines the metric that will be reported.
    # Metric names should match verbatim the identifiers created
    # during pricing setup.
    metrics:
    - name: per_broker_workload
      type: int

      # The endpoints section of a metric defines which endpoints the
      # metric data is sent to.
      endpoints:
      - name: servicecontrol

      passthrough: {}

    # The endpoints section defines where metering data is ultimately
    # sent. Currently supported endpoints include:
    # * disk - some directory on the local filesystem
    # * servicecontrol - Google Service Control
    endpoints:
    - name: servicecontrol
      servicecontrol:
        identity: gcp
        # The service name is unique to your application and will be
        # provided during onboarding.
        serviceName: pulsar-marketplace.mp-datastax-public.appspot.com
        consumerId: $AGENT_CONSUMER_ID  # From the reporting secret.
      

    # The sources section lists metric data sources run by the agent
    # itself. The currently-supported source is 'heartbeat', which
    # sends a defined value to a metric at a defined interval.
    sources:
    - name: instance_time_heartbeat
      heartbeat:
        metric: per_broker_workload
        intervalSeconds: 3600
        value:
          int64Value: 1
