apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
  - target:
      kind: CassandraDatacenter
    patch: |-
      - op: add
        path: /spec/podTemplateSpec/spec/containers/-
        value:
          name: $NAME-ubbagent
          image: $UBBAGENT_IMAGE
          env:
            - name: AGENT_CONFIG_FILE
              value: "/etc/ubbagent/config.yaml"
            - name: AGENT_LOCAL_PORT
              value: "4567"
            - name: AGENT_ENCODED_KEY
              valueFrom:
                secretKeyRef:
                  name: $REPORTING_SECRET
                  key: reporting-key
            - name: AGENT_CONSUMER_ID
              valueFrom:
                secretKeyRef:
                  name: $REPORTING_SECRET
                  key: consumer-id
          volumeMounts:
            - name: ubbagent-config
              mountPath: /etc/ubbagent
  - target:
      kind: CassandraDatacenter
    patch: |-
      - op: add
        path: /spec/podTemplateSpec/spec/volumes/-
        value:
          name: ubbagent-config
          configMap:
            name: $NAME-ubbagent-config

resources:
  - chart.yaml
