apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
  - patch: |-
      - op: replace
        path: /metadata/labels/is-crd
        value: "yes"
    target:
      kind: CustomResourceDefinition

resources:
  - chart.yaml
