apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
  - patch: |-
      - op: replace
        path: /metadata/labels/excluded-resource
        value: "yes"
    target:
      kind: ServiceAccount
      name: $NAME-grafana
  - patch: |-
      - op: replace
        path: /metadata/labels/excluded-resource
        value: "yes"
    target:
      kind: Role
      name: $NAME-grafana
  - patch: |-
      - op: replace
        path: /metadata/labels/excluded-resource
        value: "yes"
    target:
      kind: RoleBinding
      name: $NAME-grafana
  - patch: |-
      - op: replace
        path: /metadata/labels/excluded-resource
        value: "yes"
    target:
      kind: ClusterRole
      name: $NAME-grafana-clusterrole
  - patch: |-
      - op: replace
        path: /metadata/labels/excluded-resource
        value: "yes"
    target:
      kind: ClusterRoleBinding
      name: $NAME-grafana-clusterrolebinding
  - patch: |-
      - op: replace
        path: /metadata/labels/excluded-resource
        value: "yes"
    target:
      name: $NAME-grafana-test
  - patch: |-
      - op: replace
        path: /metadata/labels/excluded-resource
        value: "yes"
    target:
      kind: ServiceAccount
      name: $NAME-$KUBE_PROM_NAME-admission
  - patch: |-
      - op: replace
        path: /metadata/labels/excluded-resource
        value: "yes"
    target:
      kind: Role
      name: $NAME-$KUBE_PROM_NAME-admission
  - patch: |-
      - op: replace
        path: /metadata/labels/excluded-resource
        value: "yes"
    target:
      kind: RoleBinding
      name: $NAME-$KUBE_PROM_NAME-admission
  - patch: |-
      - op: replace
        path: /metadata/labels/excluded-resource
        value: "yes"
    target:
      kind: ClusterRole
      name: $NAME-$KUBE_PROM_NAME-admission
  - patch: |-
      - op: replace
        path: /metadata/labels/excluded-resource
        value: "yes"
    target:
      kind: ClusterRoleBinding
      name: $NAME-$KUBE_PROM_NAME-admission
  - patch: |-
      - op: replace
        path: /metadata/labels/excluded-resource
        value: "yes"
    target:
      kind: ServiceAccount
      name: $NAME-$KUBE_PROM_NAME-operator
  - patch: |-
      - op: replace
        path: /metadata/labels/excluded-resource
        value: "yes"
    target:
      kind: ClusterRole
      name: $NAME-$KUBE_PROM_NAME-operator
  - patch: |-
      - op: replace
        path: /metadata/labels/excluded-resource
        value: "yes"
    target:
      kind: ClusterRoleBinding
      name: $NAME-$KUBE_PROM_NAME-operator
  - patch: |-
      - op: replace
        path: /metadata/labels/excluded-resource
        value: "yes"
    target:
      kind: ClusterRole
      name: $NAME-$KUBE_PROM_NAME-operator-psp
  - patch: |-
      - op: replace
        path: /metadata/labels/excluded-resource
        value: "yes"
    target:
      kind: ClusterRoleBinding
      name: $NAME-$KUBE_PROM_NAME-operator-psp
  - patch: |-
      - op: replace
        path: /metadata/labels/excluded-resource
        value: "yes"
    target:
      kind: ServiceAccount
      name: $NAME-$KUBE_PROM_NAME-prometheus
  - patch: |-
      - op: replace
        path: /metadata/labels/excluded-resource
        value: "yes"
    target:
      kind: ClusterRole
      name: $NAME-$KUBE_PROM_NAME-prometheus
  - patch: |-
      - op: replace
        path: /metadata/labels/excluded-resource
        value: "yes"
    target:
      kind: ClusterRoleBinding
      name: $NAME-$KUBE_PROM_NAME-prometheus
  - patch: |-
      - op: replace
        path: /metadata/labels/excluded-resource
        value: "yes"
    target:
      kind: ClusterRole
      name: $NAME-$KUBE_PROM_NAME-prometheus-psp
  - patch: |-
      - op: replace
        path: /metadata/labels/excluded-resource
        value: "yes"
    target:
      kind: ClusterRoleBinding
      name: $NAME-$KUBE_PROM_NAME-prometheus-psp
  - patch: |-
      - op: replace
        path: /metadata/labels/excluded-resource
        value: "yes"
    target:
      kind: ServiceAccount
      name: $NAME-burnell
  - patch: |-
      - op: replace
        path: /metadata/labels/excluded-resource
        value: "yes"
    target:
      kind: ServiceAccount
      name: $NAME-function
  - patch: |-
      - op: replace
        path: /metadata/labels/excluded-resource
        value: "yes"
    target:
      kind: ServiceAccount
      name: $NAME-kube-state-metrics
  - patch: |-
      - op: replace
        path: /metadata/labels/excluded-resource
        value: "yes"
    target:
      kind: ServiceAccount
      name: $NAME-prometheus-node-exporter
  - patch: |-
      - op: replace
        path: /metadata/labels/excluded-resource
        value: "yes"
    target:
      kind: ServiceAccount
      name: $NAME-pulsarheartbeat

resources:
  - $CHART_FILE_NAME
