apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
  - patch: |-
      - op: replace
        path: /metadata/labels/requires-kube-system-namespace
        value: "yes"
    target:
      kind: Service
      name: $PROM_NAME-coredns
  - patch: |-
      - op: replace
        path: /metadata/labels/requires-kube-system-namespace
        value: "yes"
    target:
      kind: Service
      name: $PROM_NAME-kube-etcd
  - patch: |-
      - op: replace
        path: /metadata/labels/requires-kube-system-namespace
        value: "yes"
    target:
      kind: Role
      name: $NAME-cert-manager-cainjector:leaderelection
  - patch: |-
      - op: replace
        path: /metadata/labels/requires-kube-system-namespace
        value: "yes"
    target:
      kind: Role
      name: $NAME-cert-manager:leaderelection
  - patch: |-
      - op: replace
        path: /metadata/labels/requires-kube-system-namespace
        value: "yes"
    target:
      kind: RoleBinding
      name: $NAME-cert-manager-cainjector:leaderelection
  - patch: |-
      - op: replace
        path: /metadata/labels/requires-kube-system-namespace
        value: "yes"
    target:
      kind: RoleBinding
      name: $NAME-cert-manager:leaderelection

resources:
  - chart.yaml
