apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
  - patch: |-
      - op: replace
        path: /metadata/labels/requires-kube-system-namespace
        value: "yes"
    target:
      kind: Service
      name: $NAME-kube-prometheus-coredns
  - patch: |-
      - op: replace
        path: /metadata/labels/requires-kube-system-namespace
        value: "yes"
    target:
      kind: Service
      name: $NAME-kube-prometheus-kube-etcd
resources:
  - $CHART_FILE_NAME
