apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: $NAME
  excluded-resource: "no"
  is-crd: "no"
  requires-kube-system-namespace: "no"

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/serviceAccountName
        value: "$NAME-burnellserviceaccount"
    target:
      kind: Deployment
      name: "$NAME-adminconsole"
  - patch: |-
      - op: replace
        path: /spec/template/spec/serviceAccountName
        value: "$NAME-grafanaserviceaccount"
    target:
      kind: Deployment
      name: "$NAME-grafana"
  - patch: |-
      - op: replace
        path: /spec/template/spec/serviceAccountName
        value: "$NAME-kube-prometheus-admissionserviceaccount"
    target:
      kind: Job
      name: "$NAME-$KUBE_PROM_NAME-admission-create"
  - patch: |-
      - op: replace
        path: /spec/template/spec/serviceAccountName
        value: "$NAME-kube-prometheus-admissionserviceaccount"
    target:
      kind: Job
      name: "$NAME-$KUBE_PROM_NAME-admission-patch"
  - patch: |-
      - op: replace
        path: /spec/template/spec/serviceAccountName
        value: "$NAME-kube-prometheus-operatorserviceaccount"
    target:
      kind: Deployment
      name: "$NAME-$KUBE_PROM_NAME-operator"
  - patch: |-
      - op: replace
        path: /spec/serviceAccountName
        value: "$NAME-kube-prometheus-prometheusserviceaccount"
    target:
      kind: Prometheus
      name: "$NAME-$KUBE_PROM_NAME-prometheus"
  - patch: |-
      - op: replace
        path: /spec/template/spec/serviceAccountName
        value: "$NAME-burnellserviceaccount"
    target:
      kind: Deployment
      name: "$NAME-autorecovery"
  - patch: |-
      - op: replace
        path: /spec/template/spec/serviceAccountName
        value: "$NAME-functionserviceaccount"
    target:
      kind: StatefulSet
      name: "$NAME-function"
  - patch: |-
      - op: replace
        path: /spec/template/spec/serviceAccountName
        value: "$NAME-kube-state-metricsserviceaccount"
    target:
      kind: Deployment
      name: "$NAME-kube-state-metrics"
  - patch: |-
      - op: replace
        path: /spec/template/spec/serviceAccountName
        value: "$NAME-prometheus-node-exporterserviceaccount"
    target:
      kind: DaemonSet
      name: "$NAME-prometheus-node-exporter"
  - patch: |-
      - op: replace
        path: /spec/template/spec/serviceAccountName
        value: "$NAME-pulsarheartbeatserviceaccount"
    target:
      kind: Deployment
      name: "$NAME-pulsarheartbeat"

resources:
  - $CHART_FILE_NAME
