apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: $NAME
  excluded-resource: "no"
  is-crd: "no"
  requires-kube-system-namespace: "no"

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/serviceAccountName
        value: "$NAME-burnellserviceaccount"
    target:
      kind: Deployment
      name: "$NAME-adminconsole"
  - patch: |-
      - op: replace
        path: /spec/template/spec/serviceAccountName
        value: "$NAME-grafanaserviceaccount"
    target:
      kind: Deployment
      name: "$NAME-grafana"
  - patch: |-
      - op: replace
        path: /spec/template/spec/serviceAccountName
        value: "$NAME-kube-prometheus-admissionserviceaccount"
    target:
      kind: Job
      name: "$NAME-kube-prometheus-admission-create"
  - patch: |-
      - op: replace
        path: /spec/template/spec/serviceAccountName
        value: "$NAME-kube-prometheus-admissionserviceaccount"
    target:
      kind: Job
      name: "$NAME-kube-prometheus-admission-patch"
  - patch: |-
      - op: replace
        path: /spec/template/spec/serviceAccountName
        value: "$NAME-kube-promethe-operatorserviceaccount"
    target:
      kind: Deployment
      name: "$NAME-kube-promethe-operator"
  - patch: |-
      - op: replace
        path: /spec/serviceAccountName
        value: "$NAME-kube-promethe-prometheusserviceaccount"
    target:
      kind: Prometheus
      name: "$NAME-kube-promethe-prometheus"

resources:
  - $CHART_FILE_NAME
