apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: $NAME
  excluded-resource: "no"
  is-crd: "no"
  requires-kube-system-namespace: "no"

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/serviceAccountName
        value: "$BURNELL_SA"
    target:
      kind: Deployment
      name: "$NAME-adminconsole"
  - patch: |-
      - op: replace
        path: /spec/template/spec/serviceAccountName
        value: "$GRAFANA_SA"
    target:
      kind: Deployment
      name: "$GRAFANA_DEPLOYMENT"
  - patch: |-
      - op: replace
        path: /spec/template/spec/serviceAccountName
        value: "$WEBHOOK_ADMISS_SA"
    target:
      kind: Job
      name: "$WEBHOOK_ADMISS_CREATE_JOB"
  - patch: |-
      - op: replace
        path: /spec/template/spec/serviceAccountName
        value: "$WEBHOOK_ADMISS_SA"
    target:
      kind: Job
      name: "$WEBHOOK_ADMISS_PATCH_JOB"
  - patch: |-
      - op: replace
        path: /spec/template/spec/serviceAccountName
        value: "$PROM_OPERATOR_SA"
    target:
      kind: Deployment
      name: "$PROM_OPERATOR_DEPLOYMENT"
  - patch: |-
      - op: replace
        path: /spec/serviceAccountName
        value: "$PROMETHEUS_SA"
    target:
      kind: Prometheus
      name: "$PROMETHEUS_DEPLOYMENT"
  - patch: |-
      - op: replace
        path: /spec/template/spec/serviceAccountName
        value: "$BURNELL_SA"
    target:
      kind: Deployment
      name: "$NAME-autorecovery"
  - patch: |-
      - op: replace
        path: /spec/template/spec/serviceAccountName
        value: "$FUNCTION_SA"
    target:
      kind: StatefulSet
      name: "$NAME-function"
  - patch: |-
      - op: replace
        path: /spec/template/spec/serviceAccountName
        value: "$KUBE_STATE_METRICS_SA"
    target:
      kind: Deployment
      name: "$KUBE_STATE_METRICS_DEPLOYMENT"
  - patch: |-
      - op: replace
        path: /spec/template/spec/serviceAccountName
        value: "$PROM_NODE_EXPORTER_SA"
    target:
      kind: DaemonSet
      name: "$NAME-prometheus-node-exporter"
  - patch: |-
      - op: replace
        path: /spec/template/spec/serviceAccountName
        value: "$PULSAR_HEARTBEAT_SA"
    target:
      kind: Deployment
      name: "$PULSAR_HEARTBEAT_DEPLOYMENT"

resources:
  - chart.yaml
