apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
  - patch: |-
      - op: replace
        path: /data/admin-password
        value: "$GRAFANA_ADMIN_PASSWORD"
    target:
      kind: Secret
      name: "$NAME-grafana"
  - patch: |-
      - op: replace
        path: /data/password
        value: "$DASHBOARD_USER_ADMIN_PASSWORD"
    target:
      kind: Secret
      name: "dashboard-user-admin"

resources:
  - chart.yaml
